# Generated by Django 3.2.12 on 2023-11-08 00:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='humidity',
            new_name='gas_sensor',
        ),
        migrations.RemoveField(
            model_name='device',
            name='moisture_level',
        ),
        migrations.RemoveField(
            model_name='device',
            name='temperature',
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
