# Generated by Django 3.2.7 on 2023-12-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231108_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='faulty_node',
            field=models.IntegerField(default=0),
        ),
    ]
